#!/usr/bin/env bash
# Manages "manage_my_process"

if [[ ${#@} -gt 0 ]]
then
    if [[ $1 = "start" ]]
    then
        ./manage_my_process &
        echo $! > "/var/run/my_process.pid" &&\
        echo "manage_my_process started"
    elif [[ $1 = "stop" ]]
    then
        read -r pid < "/var/run/my_process.pid" && kill "$pid" &&\
        rm "/var/run/my_process.pid" && echo "manage_my_process stopped"
    elif [[ $1 = "restart" ]]
    then
        read -r pid < "/var/run/my_process.pid" && kill "$pid" &&\
        rm "/var/run/my_process.pid"
        ./manage_my_process &
        echo $! > "/var/run/my_process.pid" && echo "manage_my_process restarted"
    else echo "Usage: manage_my_process {start|stop|restart}"
    fi
else echo "Usage: manage_my_process {start|stop|restart}"
fi
