#!/usr/bin/env bash
# Display numbers 1-20. 4, 9 and 17 are bad luck

((i = 0)); while ((i < 20))
do
    ((i++))
    case $i in
        (*) echo "$i" ;;&
        (4) echo "bad luck from China" ;;
        (9) echo "bad luck from Japan" ;;
        (17) echo "bad luck from Italy" ;;
    esac
done
